sudo: required
services: 
    - docker

before_install:
    - docker build -t freiserg/react-test -f ./client/Dockerfile.dev .

script:
    - docker run freiserg/react-test npm run test -- --coverage --watchAll=false

after_success:
    - docker build -t freiserg/multi-client ./client
    - docker build -t freiserg/multi-nginx ./nginx
    - docker build -t freiserg/multi-server ./server
    - docker build -t freiserg/multi-worker ./worker
