sudo: required
services: 
    - docker

before_install:
    - docker build -t freiserg/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run freiserg/react-test npm run test -- --coverage --watchAll=false

after_success:
    - docker build -t freiserg/multi-client ./client
    - docker build -t freiserg/multi-nginx ./nginx
    - docker build -t freiserg/multi-server ./server
    - docker build -t freiserg/multi-worker ./worker
    # Login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push
    - docker push freiserg/multi-client
    - docker push freiserg/multi-nginx
    - docker push freiserg/multi-server
    - docker push freiserg/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-920038863434"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

